<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BG5CG9014307" name="com.test_suites.examples.TC_02_Example_HttpClient.Fly.ID_02_RegisterUser" tests="1" failures="1" timestamp="30 Apr 2019 07:46:01 GMT" time="0.473" errors="0">
  <testcase name="signIn" time="0.473" classname="com.test_suites.examples.TC_02_Example_HttpClient.Fly.ID_02_RegisterUser">
    <failure type="java.lang.AssertionError" message="expected [OK] but found [Unauthorized]">
        <![CDATA[java.lang.AssertionError: expected [OK] but found [Unauthorized]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.test_suites.examples.TC_02_Example_HttpClient.Fly.ID_02_RegisterUser.signIn(ID_02_SignIn.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- signIn -->
</testsuite> <!-- com.scriptspts.examples.TC_02_Example_HttpClient.ID_02_RegisterUsererUser -->
